### ISSUE TITLE
Nick Plugin

### ISSUE THREAD

**Issue by ThexXTURBOXx** [Rustco-Network/ToDo#2]
- [x] Ein "zu Hause" funktionierendes Nick-Plugin schreiben
- [x] Test auf dem Hauptserver
- [x] Random Nicks perfektionieren
- [x] Skins funktionieren nicht
- [x] Integration für das NickItem-Plugin
- [x] Fertig

Fortschritt: https://github.com/Rustico-Network/Nick

**Comment by reesn** [comment]
Gut, das ist eine gute Idee um dieses Plugin zu schreiben.

**Comment by ThexXTURBOXx** [comment]
Bin mal gespannt, ob des Plugin, so wie es is, auch auf dem Server funktioniert...

**Comment by ThexXTURBOXx** [comment]
Endlich :)
